
title: Aashish Aadarsh
url: 'https://aashish-aadarsh.github.io'
baseurl: 'aashish-aadarsh.github.io'



# Profile information
yourname: Aashish Aadarsh
title: 'Senior Developer'
location: Bengaluru ,Karnataka
description: A computer science professional skilled in Java, Spring Boot and Android App Development. 
              Strong engineering professional, domain knowledge. Currently working in Mindtree Ltd. 


## Social Profiles
facebook: http://www.facebook.com  ## your facebook account url
twitter: http://www.twitter.com  ## your twitter account url
linkedin: http://www.linkedin.com/in/aadarshbgp
github: https://github.com/aashish-aadarsh
stackoverflow: https://stackoverflow.com/users/5028082/aashish-aadarsh
