# Site settings
title: Aashish Aadarsh
description: My Portfolio
favicon: /assets/img/avatar.png
baseurl: aashish-aadarsh.github.io
url: https://aashish-aadarsh.github.io
rss_url: /pages/atom.xml
google_analytics: UA-63653234-1

# Build settings
markdown: kramdown

exclude: [vendor]

# Author settings
author:
  name: Aashish Aadarsh
  title: Senior FullStack Developer
  address: Bengaluru, Karnataka
  email: aashish.aadarsh@outlook.com
  link: https://aashish-aadarsh.github.io
  github: aashish-aadarsh
  twitter: aa_aadarsh
  linkedin: aadarshbgp
  gavatar: /resumecard/assets/img/avatar.png
  stackoverflow: 5028082/aashish-aadarsh

  workHistory:
    - work1:
      company: XXX Ltd
      location: Auckland, New Zealand
      title: Java Developer
      started: 2014
      duration: (2014 - Present)
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
    - work2:
      company: XXX Ltd
      location: Shanghai, China
      title: Java Developer
      started: 2012
      duration: (2012 - 2014)
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
    - work3:
      company: XXX Ltd
      location: Shanghai, China
      title: Java Developer
      started: 2009
      duration: (2009 - 2012)
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
  educationHistory:
    - education1:
      organization: Bhagalpur College of Engineering
      location: Bhagalpur, Bihar
      degree: Bachelor of Technology
      major: Computer Science & Engineering
      started: 2005
      duration: (2010 - 2014)
  languages:
    - language1:
      name: English
      proficiency: Professional
    - language2:
      name: Hindi
      proficiency: Native
  programmingSkills:
    - skill1:
      name: Android
      percentage: 90%
    - skill2:
      name: Java, Spring-Boot, Hibernate
      percentage: 80%
    - skill3:
      name: JavaScript
      percentage: 70%
    - skill4:
      name: MySQL, MongoDB, Neo4j
      percentage: 70%
    - skill5:
      name: Docker, Jenkins
      percentage: 70%
